[env:esp32dev]
platform = espressif32@6.7.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^7.1.0
  beegee-tokyo/DHT sensor library for ESPx@^1.19.0
build_flags =
  -D CORE_DEBUG_LEVEL=3
